services:
  influxdb2:
    image: influxdb:2
    container_name: influxdb_ct1
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
      - ./influxdb_config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: token123
      DOCKER_INFLUXDB_INIT_ORG: technbd
      DOCKER_INFLUXDB_INIT_BUCKET: home
  grafana:
    image: grafana/grafana
    container_name: grafana_ct1
    ports:
      - "3000:3000"
    user: '0'
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin321
    depends_on:
      - influxdb2
